sudo: required
dist: trusty

language: node_js
node_js:
  - "10"

services:
  - docker

install:
  - npm ci .
  - npm run test

script:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && travis_retry docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    npm prune --production &&
    travis_retry docker build -t $DOCKER_USERNAME/$SERVICE:$TRAVIS_BRANCH -f ./docker/Dockerfile . &&
    travis_retry docker push $DOCKER_USERNAME/$SERVICE:$TRAVIS_BRANCH 

after_success: true
