version: 2 # use CircleCI 2.0
jobs:
  test:
    working_directory: ~/apex
    docker: # run the steps with Docker
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Test
          command: npm test

  deploy:
    working_directory: ~/apex
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Build for DockerHub
          command: |
            docker build -t $DOCKER_USERNAME/apex-api:$CIRCLE_BRANCH -f ./docker/Dockerfile .
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push $DOCKER_USERNAME/apex-api:$CIRCLE_BRANCH
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master